version: '3'
services:
  db:
    image: mysql
    environment:
      # TODO: set up root pw in an includable file or setup non-root user/pw
      MYSQL_ROOT_PASSWORD: trololol
    volumes:
    # docker auto-runs all .sql or .sql.gz files in this path.
     - ../../db/bootstrap:/docker-entrypoint-initdb.d
  app:
    image: golang:1.9
    volumes:
      - ../../../:/go/src/github.com/willdobbins/notes
    ports:
      - 8080:8080
      - 3000:3000
    links:
      - db
    working_dir: /go/src/github.com/willdobbins/notes
    command: ./startup.sh
